m4_define([AT_PACKAGE_NAME],	  [Open-COBOL-ESQL])
m4_define([AT_PACKAGE_TARNAME],	  [Open-COBOL-ESQL-1.2])
m4_define([AT_PACKAGE_VERSION],	  [1.2])
m4_define([AT_PACKAGE_STRING],	  [Open-COBOL-ESQL-1.2])
m4_define([AT_PACKAGE_BUGREPORT], [ws-opensource-cobol-contact@osscons.jp])